from panda3d.core import Vec3

MOVEMENT_SPEED = 3
BASE_HEALTH = 10
GRAVITY = 9.81*2
JUMP_VELOCITY = 10
POST_HIT_INV_DURATION = 0.5
BLOCK_RANGE_DEG = 180
DASH_SPEED = 20
WORLD_CENTER_POINT = (0,4)
ALLOWED_WORD_CENTER_DISTANCE = 13

PLAYER_1_SPAWN = (0,-5)
PLAYER_2_SPAWN = (0,9)

BOT_WAIT_TIME_BETWEEN_ACTION_CHECKS = 1

MAIN_MENU_CAMERA_ROTATION_SPEED = 0.25
MAIN_MENU_PLAYER_POSITION = Vec3(0,2,0.5)
MAIN_MENU_CAMERA_HEIGHT = 4
MAIN_MENU_CAMERA_ROTATION_RADIUS = 7
