name: build-and-release

on:
  push:
    tags:
    - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        os: [windows, ubuntu, macos]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install panda
        run: python3 -m pip install -r requirements.txt

      - name: Install Setuptools
        run: python3 -m pip install setuptools --break-system-packages

      - name: build
        run: python3 setup.py build_apps 

      - name: prep macos 
        if: ${{ matrix.os == 'macos' }}
        run: |
          mkdir ./artifact
          cp -r ./build/macosx_10_9_x86_64/* ./artifact/

      - name: prep linux
        if: ${{ matrix.os == 'ubuntu' }}
        run: |
          mkdir ./artifact 
          cp -r ./build/manylinux2014_x86_64/ ./artifact/build 
          echo "cd ./build && ./flow" > ./artifact/flow
          chmod +x ./artifact/build/flow 
          chmod +x ./artifact/flow 

      - name: prep windows
        if: ${{ matrix.os == 'windows' }}
        run: |
          Copy-Item -Path .\build\win_amd64 -Destination .\artifact -Recurse;
        shell: pwsh

      - uses: actions/upload-artifact@v4
        with:
          name: flow_${{ matrix.os }}
          path: ./artifact/

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: build

      - run: zip -r linux.zip build/flow_ubuntu

      - run: zip -r windows.zip build/flow_windows

      - run: zip -r macos.zip build/flow_macos

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            linux.zip
            macos.zip
            windows.zip
